name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - claraa

jobs:
  build:
    runs-on: self-hosted
    container:
      image: ubuntu:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build the Docker image
        run: docker build -t fulkiaaa/cicdpipeline:latest .

      - name: Push to DockerHub
        run: docker push fulkiaaa/cicdpipeline:latest
