name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - alexandre-test

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # - name: install dependencies
      #   id: npm_install
      # - run: npm install

      # - name: test unit
      #   if: steps.npm_install.outcome == 'success'
      # - run: npm test

      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm ci
      - run: npm run test

      - name: Login to DockerHub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build the Docker image
        run: docker build -t fulkiaaa/cicdpipeline:latest .

      - name: Push to DockerHub
        run: docker push fulkiaaa/cicdpipeline:latest
