name: Build and Push Docker Image to Docker Hub

on: push
jobs:
  build:
    - name: Login DockerHub
      env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Build the Docker image
      run: docker build -t fulkiaaa/cicdpipeline:latest

    - name: Push to DockerHub
      run: docker push fulkiaaa/cicdpipeline:latest
    
